<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Les Amoureux du Chocolat - Acceuil</title>
    <link rel="icon" href="img/logo_header.png">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
    <link rel="stylesheet" href="css/icons.css" type="text/css">
    <link rel="stylesheet" href="css/normalize.css" type="text/css">
    <link rel="stylesheet" href="css/main.css" type="text/css">
</head>

<body>
    <!--HAUT DE PAGE-->
    <header>
        <!--START INFOS HOURS-->
        <div class="info">
            <p>Durant le confinement, nous continuons à vous acceuillir aux jours et horaires d'ouverture habituels: du
                mardi au samedi de 09H30 à 19H30.
                <!-- Nous vous remercions par avance pour votre soutien, prenez soin de vous et à bientôt!-->
            </p>
        </div>
        <!-- END INFOS HOURS -->
        <!-- START MENUS LOGIN-->
        <div class="login">
            <div class="nav-login">
                <ul class="pogo">
                    <!--<li><a href="#">Recherche</a></li>-->
                    <li><a href="index.php"><i class="fas fa-heart"></i>Acceuil</a>
                    <li><a href="about_us.php"> Qui nous sommes? </a>
                    </li>
                    <?php if (empty($_SESSION['role'])) {?>
                    <li><a href="login.php"><i class="fas fa-user"></i> Connection </a></li>
                    <li><a href="register.php"><i class="fas fa-user"></i> S'enregistrer </a></li>
                    <?php } else {?>
                    <li><a href="info.php"><i class="fas fa-user"></i> Mon compte <?= $_SESSION['firstName'] ?></a></li>
                    <li><a href="logout.php"><i class="fas fa-shopping-basket"></i> Déconexion </a></li>
                    <?php } ?>
                    <li><a href="#"><i class="fas fa-shopping-basket"></i> Panier </a></li>
                </ul>
            </div>
        </div>
        <!--END MENUS LOGIN-->
        <!--LOGO-->
        <div class="heart logo">
            <a href="index.phtml"><img class="logo" src="img/les-amoureux-du-chocolat-logo.png"></a>
        </div>
        <!--END LOGO-->
        <!--START SEARCH BAR-->
        <div class="search">
            <?php if (array_key_exists( 'role', $_SESSION)) {?>
            <h1><img class="" src=""></h1>
            <?php } else { ?>
            <!-- <p>Vous n'êtes pas connectés<img class="img-main" src="img/wifi-off.svg"></p> -->
            <a href="login.php">
                <h2 class="merci-id">Merci de vous Identifiez</h2>
            </a>
            <?php } ?>
            <form action="" method="">
                <label for="product name"></label>
                <input type="text" placeholder="Recherche"><button class="btn-letter" type="submit">
                    <i class="fas fa-search"></i></button>
            </form>
        </div>
        <!--END SEARCH BAR-->
        <!--MENUS nav Produits-->
        <nav>
            <ul>
                <li>
                    <a href="#">CHOCOLAT & FRUITS SECS</a>
                    <div class="menu">
                        <a href="products.phtml">Amandines Noir ou Lait</a>
                        <a href="products.phtml">Chocolat de couverture Noir ou Lait</a>
                        <a href="products.phtml">Coeurs de biscuit enrobés de chocolat au lait</a>
                        <a href="products.phtml">Croc'Amande Noir ou Lait</a>
                        <a href="products.phtml">Croc'Noisette Noir ou lait</a>
                        <a href="products.phtml">Grignotines</a>
                        <a href="products.phtml">Mendiants Noir ou Lait</a>
                        <a href="products.phtml">Noisettes gianduja</a>
                        <a href="products.phtml">Noisettines Noir Lait ou Blanc praliné</a>
                        <a href="products.phtml">Palets au grué de cacao</a>
                        <a href="products.phtml">Palets Cranberry noir</a>
                    </div>
                </li>
                <li>
                    <a href="#">NOS COFFRETS & ATELIER</a>
                    <div class="menu">
                        <a href="products.phtml">Coffret noir de 16 à 64 Chocolats</a>
                        <a href="products.phtml">Coffret noir et lait de 16 à 64 Chocolats</a>
                        <a href="products.phtml">Atelier découverte</a>
                        <a href="products.phtml">Atelier enfant</a>
                        <a href="products.phtml">Atelier gourmet</a>
                    </div>
                </li>
                <li>
                    <a href="#">CONFISERIES & CONFITES</a>
                    <div class="menu">
                        <a href="products.phtml">Assortiment de pâtes de fruits 100g</a>
                        <a href="products.phtml">Assortiment de pâtes de fruits 160g</a>
                        <a href="products.phtml">Caramels mous fleur de sel framboise sésame</a>
                        <a href="products.phtml">Guimauves vanille, framboise</a>
                        <a href="products.phtml">Sucette lait</a>
                        <a href="products.phtml">Sucette noir</a>
                        <a href="products.phtml">Clémentines confites one</a>
                        <a href="products.phtml">Clémentines confitesbox</a>
                    </div>
                </li>
                <li>
                    <a href="#">GANACHES & ORANGETTES CITRONNETTES</a>
                    <div class="menu">
                        <a href="products.phtml">Basilic</a>
                        <a href="products.ph.tml">Café noir</a>
                        <a href="products.phtml">Citron</a>
                        <a href="products.phtml">Earl Grey noir</a>
                        <a href="products.phtml">Framboise</a>
                        <a href="products.phtml">Jasmin</a>
                        <a href="products.phtml">L'amoureux noir</a>
                        <a href="products.phtml">Menthe</a>
                        <a href="products.phtml">Passion</a>
                        <a href="products.phtml">Venezuela 72%</a>
                        <a href="products.phtml">Vietnam 64%</a>
                        <a href="products.phtml">Citronnettes</a>
                        <a href="products.phtml">Gingembrettes</a>
                        <a href="products.phtml">Orangettes</a>
                    </div>
                </li>
                <li>
                    <a href="#">MADELEINES BISCUITS & LES PÂTES À TARTINER</a>
                    <div class="menu">
                        <a href="products.phtml">Madeleines Noir ou lait</a>
                        <a href="products.phtml">Madeleines noir</a>
                        <a href="products.phtml">Biscuits noisette à la pâte à tartiner</a>
                        <a href="products.phtml">Caramel fleur de sel</a>
                        <a href="products.phtml">Pâte à tartiner à la noisette Piémont</a>
                    </div>
                </li>
                <li>
                    <a href="#">PRALINÉS</a>
                    <div class="menu">
                        <a href="products.phtml">Praliné Amandes Lait</a>
                        <a href="products.phtml">Praliné Amandes & Noisettes Noir ou Lait</a>
                        <a href="products.phtml">Praliné Praliné Amandes & Noisettes Noir</a>
                        <a href="products.phtml">Praliné Feuilletine Noir ou Lait</a>
                        <a href="products.phtml">Praliné Cacahuètes Noir ou Lait</a>
                        <a href="products.phtml">Praliné Coco Noir ou Lait</a>
                        <a href="products.phtml">Praliné Feuilletine Lait</a>
                        <a href="products.phtml">Praliné Noisettes Piémont Noir ou Lait</a>
                        <a href="products.phtml">Praliné Noix de pécan et fleur de sel</a>
                        <a href="products.phtml">Praliné Pignons de pin Noir ou Lait</a>
                        <a href="products.phtml">Praliné Sésame Noir ou Lait</a>
                    </div>
                </li>
                <li>
                    <a href="#">TABLETTES & MOULES</a>
                    <div class="menu">
                        <a href="products.phtml">Tablette Bali 68%</a>
                        <a href="products.phtml">Tablette Bélize 75%</a>
                        <a href="products.phtml">Tablette Grenade 65%</a>
                        <a href="products.phtml">Tablette lait République Dominicaine 46%</a>
                        <a href="products.phtml">Tablette Madagascar 50%</a>
                        <a href="products.phtml">Tablette Madagascar 68%</a>
                        <a href="products.phtml">Tablette Venezuela 72%</a>
                        <a href="products.phtml">Tablette Pérou 70%</a>
                        <a href="products.phtml">Tablette sans sucre 72%</a>
                        <a href="products.phtml">Tablette Venezuela 100%</a>
                        <a href="products.phtml">Tablette Vietnam 64%</a>
                        <a href="products.phtml">Animaux</a>
                        <a href="products.phtml">Oeuf Noir et Lait</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <main class="container">
        <?php include 'www/'.$template.'.phtml';?>
        <!-- include 'www/index.phtml';-->
    </main>
    <!--FOOTER-->
    <footer>
        <h4>LA NEWSLETTER !</h4>
        <div class="container-footer">
            <div class="lettre">
                <fieldset>
                    <label for="lettre"></label> <!-- <i class="fas fa-envelope"></i> -->
                    <input type="text" id="lettre" placeholder="Votre adresse e-mail" required>
                    <button class="btn-letter" type="submit">S'inscrire</button>
                </fieldset>
            </div>

            <div class="bloc footer-conditions">
                <h5>INFORMATIONS</h5>
                <ul class="conditions">
                    <li><a href="#">Mentions légales </a></li>
                    <li><a href="#">Conditions de livraison </a></li>
                    <li><a href="#">Conditions générales de vente </a></li>
                    <li><a href="#">Paiements sécurisés </a></li>
                    <li><a href="#">Politique d'utilisation des cookies </a></li>
                </ul>
            </div>

            <div class="bloc footer-paiement">
                <h5>VOS ACHATS</h5>
                <ul class="paiement">
                    <li><a href="#">PAIEMENT SÉCURISÉ <i class="fas fa-lock"></i></a></li>
                    <li><a href="#">CONDITIONS DE LIVRAISON <i class="fas fa-truck"></i></a></li>
                    <li><a href="#">RETRAIT EN BOUTIQUE <i class="fas fa-store-alt"></i></a></li>
                </ul>
            </div>

            <div class="bloc footer-media">
                <h5>SUIVEZ-NOUS</h5>
                <ul class="media">
                    <li> <a target="_blanck" href="https://www.facebook.com/lesamoureuxduchocolat"><i
                                class="fab fa-facebook"></i></a></li>
                    <li><a target="_blanck" href="https://www.instagram.com/lesamoureuxduchocolat/"><i
                                class="fab fa-instagram"></i></a></li>
                </ul>
            </div>

            <div>
                <p>Copyright © 2015 par Les Amoureux du Chocolat. Tous droits réservés. 812 329 936 R.C.S Evry</p>
            </div>
        </div>
    </footer>
    <!--END of FOOTER-->

    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/jquery.backtotop.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>


</body>

</html>