<img class="us" src="img/nous.png" id="nous" alt="artisants">
<div class="text">

</div>
<aside class="area-side">
    <p>Dès son plus jeune âge, Johan est déjà fasciné par l'univers du chocolat et des gourmandises. Il
        obtient très vite ses diplômes des métiers de la restauration et de l'hôtellerie, puis ceux de
        chocolatier et pâtissier (glacier, confiseur).
        Il suit sa formation auprès de <strong>Ladurée</strong> à Paris, puis de Marquise et Tradition dans
        l'Essonne. Là,
        naît sa grande passion pour le chocolat.</p>
    <p>Il part ensuite en Normandie peaufiner son expérience dans la chocolaterie <strong>Les Kabosses</strong>,
        avec le chef
        chocolatier Jean-Michel K'Dual. Puis il décide alors de partir découvrir de nouvelles techniques en
        Australie. C'est là que Johan et
        Claire ont fondu l'un pour l'autre, dans une grande chocolaterie australienne. De là est née une
        histoire d'amour, une passion commune pour le chocolat.</p>
    <p> Ensemble, ils décident de rejoindre la France pour faire partager cette expérience à travers la
        chocolaterie Les Amoureux du Chocolat. Tous les deux s'harmonisent avec perfection pour vous faire
        partager de merveilleux moments chocolatés.
    </p>
</aside>
<a target="_blanck" href="https://www.lespapillesdor.fr/commercants/les-amoureux-du-chocolat"><img
        src="img/lespapillesdor-annees.png" id="papilles17" alt="Logo papilles 2017-18-19-20"></a>
<a target="_blanck" href="https://www.croqueurschocolat.com/"><img src="img/Croqueurs-de-chocolat.png" id="croqueur"
        alt="Club des croqueurs"></a>
<aside></aside>
<!--START BUTTON TOP-->
<div class="top"></div>
<a id="backtotop"><i class="fas fa-chevron-up"></i></a>
<!--END BUTTON TOP-->