<?php if ($test != '') { ?>
<div>
    <?php if ($test == 'yes') {?>
    <p>mail envoyé</p>
    <a href="index.php">Retourner sur l'accueil</a>
    <?php } else if ($test == 'no'){?>
    <p>email inconnu</p>
    <?php } ?>
</div>
<?php } ?>

<form action="forgotPassword.php" method="post">
    <input type="text" placeholder="email" name="email" />
    <input type="submit" value="Envoyer un mail" />
</form>