<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Les Amoureux du Chocolat/ACCEUIL</title>
    <link rel="icon" href="img/logo_header.png">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="js/main.js" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    <link rel="stylesheet" href="css/slick.css">
    <link rel="stylesheet" href="css/slick-theme.css">
    <link rel="stylesheet" href="css/icons.css" type="text/css">
    <link rel="stylesheet" href="css/main.css" type="text/css">
</head>

<body>
    <!--HAUT DE PAGE-->
    <header class="bgtop">
        <!-- <video controls loop> <source src="medias/production ID_5152004.mp4" type="video/mp4"> </video>-->

        <!--MENUS Login-->
        <nav>
            <ul>
                <!--<li><a href="#">Recherche</a></li>-->
                <li><a href="about_us.phtml"><i class="fas fa-heart"></i> Qui nous sommes?</a>
                </li>
                <li><a href="#"><i class="fas fa-user"></i>Mon compte</a></li>
                <li><a href="#"><i class="fas fa-shopping-basket"></i> Panier</a></li>

            </ul>
        </nav>

        <div>
            <a href="index.phtml"><img class="logo" src="img/les-amoureux-du-chocolat-logo.jpg"></a>
        </div>
        <!---->
        <!--MENUS nav Produits-->
        <nav class="nav">
            <ul class="nav-content">
                <li class="nav-item"><a href="#CHOCOLAT & FRUITS SECS">CHOCOLAT & FRUITS SECS</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Amandines Noir ou Lait</a></li>
                        <li><a href="products.phtml">Chocolat de couverture Noir ou Lait</a></li>
                        <li><a href="products.phtml">Coeurs de biscuit enrobés de chocolat au lait</a></li>
                        <li><a href="products.phtml">Croc'Amande Noir ou Lait</a></li>
                        <li><a href="products.phtml">Croc'Noisette Noir ou lait</a></li>
                        <li><a href="products.phtml">Grignotines</a></li>
                        <li><a href="products.phtml">Mendiants Noir ou Lait</a></li>
                        <li><a href="products.phtml">Noisettes gianduja</a></li>
                        <li><a href="products.phtml">Noisettines Noir Lait ou Blanc praliné</a></li>
                        <li><a href="products.phtml">Palets au grué de cacao</a></li>
                        <li><a href="products.phtml">Palets Cranberry noir</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#NOS COFFRETS">NOS COFFRETS</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Coffret noir de 16 à 64 Chocolats</a></li>
                        <li><a href="products.phtml">Coffret noir et lait de 16 à 64 Chocolats</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#CONFISERIES ">CONFISERIES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Assortiment de pâtes de fruits 100g</a></li>
                        <li><a href="products.phtml">Assortiment de pâtes de fruits 160g</a></li>
                        <li><a href="products.phtml">Caramels mous fleur de sel framboise sésame</a></li>
                        <li><a href="products.phtml">Guimauves vanille, framboise</a></li>
                        <li><a href="products.phtml">Sucette lait</a></li>
                        <li><a href="products.phtml">Sucette noir</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#CONFITES">CONFITES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Clémentines confites one</a></li>
                        <li><a href="products.phtml">Clémentines confitesbox</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#GANACHES">GANACHES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Basilic</a></li>
                        <li><a href="products.ph.tml">Café noir</a></li>
                        <li><a href="products.phtml">Citron</a></li>
                        <li><a href="products.phtml">Earl Grey noir</a></li>
                        <li><a href="products.phtml">Framboise</a></li>
                        <li><a href="products.phtml">Jasmin</a></li>
                        <li><a href="products.phtml">L'amoureux noir</a></li>
                        <li><a href="products.phtml">Menthe</a></li>
                        <li><a href="products.phtml">Passion</a></li>
                        <li><a href="products.phtml">Venezuela 72%</a></li>
                        <li><a href="products.phtml">Vietnam 64%</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#LES PÂTES À TARTINER">LES PÂTES À TARTINER</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Caramel fleur de sel</a></li>
                        <li><a href="products.phtml">Pâte à tartiner à la noisette Piémont</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#MADELEINES & BISCUITS">MADELEINES & BISCUITS</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Biscuits noisette à la pâte à tartiner</a></li>
                        <li><a href="products.phtml">Madeleines Noir ou lait</a></li>
                        <li><a href="products.phtml">Madeleines noir</a></li>
                    </ul>
                </li>

                <li class="nav-item"><a href="#MOULES">MOULES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Animaux</a></li>
                        <li><a href="products.phtml">Oeuf Noir et Lait</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#ORANGETTES et CITRONNETTES">ORANGETTES et CITRONNETTES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Citronnettes</a></li>
                        <li><a href="products.phtml">Gingembrettes</a></li>
                        <li><a href="products.phtml">Orangettes</a></li>
                    </ul>
                </li>

                <li class="nav-item"><a href="#PRALINÉS">PRALINÉS</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Praliné Amandes Lait</a></li>
                        <li><a href="products.phtml">Praliné Amandes & Noisettes Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Praliné Amandes & Noisettes Noir</a></li>
                        <li><a href="products.phtml">Praliné Feuilletine Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Cacahuètes Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Coco Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Feuilletine Lait</a></li>
                        <li><a href="products.phtml">Praliné Noisettes Piémont Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Noix de pécan et fleur de sel</a></li>
                        <li><a href="products.phtml">Praliné Pignons de pin Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Sésame Noir ou Lait</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#TABLETTES">TABLETTES</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Tablette Bali 68%</a></li>
                        <li><a href="products.phtml">Tablette Bélize 75%</a></li>
                        <li><a href="products.phtml">Tablette Grenade 65%</a></li>
                        <li><a href="products.phtml">Tablette lait République Dominicaine 46%</a></li>
                        <li><a href="products.phtml">Tablette Madagascar 50%</a></li>
                        <li><a href="products.phtml">Tablette Madagascar 68%</a></li>
                        <li><a href="products.phtml">Tablette Venezuela 72%</a></li>
                        <li><a href="products.phtml">Tablette Pérou 70%</a></li>
                        <li><a href="products.phtml">Tablette sans sucre 72%</a></li>
                        <li><a href="products.phtml">Tablette Venezuela 100%</a></li>
                        <li><a href="products.phtml">Tablette Vietnam 64%</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="#ATELIER">ATELIER</a>
                    <ul class="submenu">
                        <li><a href="products.phtml">Atelier découverte</a></li>
                        <li><a href="products.phtml">Atelier enfant</a></li>
                        <li><a href="products.phtml">Atelier gourmet</a></li>
                    </ul>
                </li>
        </nav>
    </header>

    <main>
        <h1>Contactez-nous!</h1>
        <p class="welcome">La chocolaterie vous accueille du mardi au samedi de 9h30 à 19h30.</p>
        <form action="#" method="post">
            <div>
                <div class="lettre">
                    <fieldset>
                        <label for="lettre">Lettre d'informations</label>
                        <input type="text" id="lettre" placeholder="Saisissez votre adresse e-mail" required>
                    </fieldset>
                </div>
                <fieldset>
                    <label for="Nom">Nom*</label>
                    <input type="text" id="nom" placeholder="" required>
                    <label for="Prénom">Prénom*</label>
                    <input type="text" id="prenom" placeholder="" required>
                    <label for="E-mail">E-mail*</label>
                    <input type="E-mail" placeholder="" id="email">
                    <label for="Téléphone">Téléphone</label>
                    <input type="Téléphone" placeholder="" id="tel" not required>
                    <label for="Message">Message*</label>
                    <input type="Message" id="message" placeholder="" required>
                </fieldset>

                <div class="adr">
                    <i class="fas fa-map-marker-alt">
                        <p>Chocolaterie Les Amoureux du Chocolat, 9 Place de l'Union Européenne 91300 Massy</p>
                    </i>
                    <i class="fas fa-phone-square-alt">
                        <p>Appelez-nous au : 01 85 41 05 43</p>
                    </i>
                    <i class="fas fa-envelope">
                        <p>E-mail : contact@lesamoureuxduchocolat.com</p>
                    </i>
                </div>

                <a href="#"> Mentions légales</a>
                <a href="#">Conditions de livraison</a>
                <a href="#">Conditions générales de vente</a>
                <a href="#">Paiements sécurisés</a>

    </main>
    <footer>
        <div>
            <a href="#">PAIEMENT SÉCURISÉ <i class="fas fa-lock"></i></a>
            <a href="#">CONDITIONS DE LIVRAISON <i class="fas fa-truck"></i></a>
            <a href="#">RETRAIT EN BOUTIQUE <i class="fas fa-store-alt"></i></a>
        </div>

        <div class="contact">
            <a href="">
                <h4>Informations</h4>
            </a>
            <a href="#"> Mentions légales</a>
            <a href="#">Conditions de livraison</a>
            <a href="#">Conditions générales de vente</a>
            <a href="#">Paiements sécurisés</a>
            <a href="#">Politique d'utilisation des cookies</a>
        </div>

        <div>
            <p>© 2015 par Les Amoureux du Chocolat. Tous droits réservés. 812 329 936 R.C.S Evry</p>
        </div>

        <div>
            <a target="_blanck" href="https://www.facebook.com/lesamoureuxduchocolat"><i
                    class="fab fa-facebook"></i></a>
            <a target="_blanck" href="https://www.instagram.com/lesamoureuxduchocolat/"><i
                    class="fab fa-instagram"></i></a>
        </div>
    </footer>
</body>

</html>