<div class="contact">

    <h1>Informations sur votre boutique</h1>
    <img src="apropos-de-nous-acceuil.png" alt="boutique-pic">
    <!-- <img src="apropos-de-nous-acceuil1.1.png" alt="boutique-pic">
    <img src="apropos-de-nous-boutique1.png" alt="boutique-pic"> -->
    <!-- <center>
        <div class="slider"> -->
    <!-- ?php foreach($products as $product): ?
            <img src="?= $product['Photos']?>" alt="?= $product['Name'] ?">
            ?php endforeach ? -->
    <!-- </div>
    </center> -->




    <div class="adress">
        <h6>NOTRE ADRESSE</h6>
        <ul>
            <li>Chocolaterie Les Amoureux du Chocolat</li>
            <li>9 Place de l'Union Européenne</li>
            <li>91300 Massy</li>
        </ul>
    </div>
    <div class="mag-contacter">
        <h6>NOUS CONTACTER</h6>
        <ul>
            <li>E-mail : contact@lesamoureuxduchocolat.com</li>
            <li>Téléphone : 01 85 41 05 43</li>

        </ul>
    </div>
    <div class="hours">
        <h6>HORAIRES D'OUVERTURES</h6>
        <ul>
            <li>Lundi : boutique fermé</li>
            <li>Mardi : 09:30-19:30</li>
            <li>Mercredi : 09:30-19:30 </li>
            <li>Jeudi : 09:30-19:30 </li>
            <li>Vendredi : 09:30-19:30 </li>
            <li>Samedi : 09:30-19:30 </li>
            <li>Dimanche : 09:30-13:00</li>
        </ul>
    </div>



    <a id="backtotop"><i class="fas fa-chevron-up"></i></a>




















































</div>