<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Les Amoureux du Chocolat - Acceuil</title>
    <link rel="icon" href="img/logo_header.png">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
    <link rel="stylesheet" href="css/icons.css" type="text/css">
    <link rel="stylesheet" href="css/main.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>

</head>

<body>
    <!--HAUT DE PAGE-->
    <header>
        <!-- <video controls loop> <source src="medias/production ID_5152004.mp4" type="video/mp4"> </video>-->
        <!--START INFOS HOURS-->
        <div class="info">
            <p>Durant le confinement, nous continuons à vous acceuillir aux jours et horaires d'ouverture habituels: du
                mardi au samedi de 09H30 à 19H30.
                <!-- Nous vous remercions par avance pour votre soutien, prenez soin de vous et à bientôt!-->

            </p>
        </div>
        <!-- END INFOS HOURS -->
        <!-- START MENUS LOGIN-->
        <div class="login">
            <nav class="nav-login">
                <ul>
                    <!--<li><a href="#">Recherche</a></li>-->
                    <li><a href="about_us.phtml"><i class="fas fa-heart"></i> Qui nous sommes? </a>
                    </li>
                    <li><a href="#"><i class="fas fa-user"></i> Mon compte </a></li>
                    <li><a href="#"><i class="fas fa-shopping-basket"></i> Panier </a></li>
                </ul>
            </nav>
        </div>
        <!--END MENUS LOGIN-->
        <!--LOGO-->
        <div class="heart logo">
            <a href="index.phtml"><img class="logo" src="img/les-amoureux-du-chocolat-logo.png"></a>
        </div>
        <!--END LOGO-->
        <!--START SEARCH BAR-->
        <div class="search">
            <form action="" method="">
                <label for="product name"></label>
                <input type="text" placeholder="Recherche"><button class="btn-letter" type="submit"><i
                        class="fas fa-search"></i></button>
        </div>
        <!--END SEARCH BAR-->
        <!--MENUS nav Produits-->
        <nav>
            <ul>
                <li class="nav-bar"><a href="#CHOCOLAT & FRUITS SECS">CHOCOLAT & FRUITS SECS</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Amandines Noir ou Lait</a></li>
                        <li><a href="products.phtml">Chocolat de couverture Noir ou Lait</a></li>
                        <li><a href="products.phtml">Coeurs de biscuit enrobés de chocolat au lait</a></li>
                        <li><a href="products.phtml">Croc'Amande Noir ou Lait</a></li>
                        <li><a href="products.phtml">Croc'Noisette Noir ou lait</a></li>
                        <li><a href="products.phtml">Grignotines</a></li>
                        <li><a href="products.phtml">Mendiants Noir ou Lait</a></li>
                        <li><a href="products.phtml">Noisettes gianduja</a></li>
                        <li><a href="products.phtml">Noisettines Noir Lait ou Blanc praliné</a></li>
                        <li><a href="products.phtml">Palets au grué de cacao</a></li>
                        <li><a href="products.phtml">Palets Cranberry noir</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#NOS COFFRETS & ATELIER">NOS COFFRETS & ATELIER</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Coffret noir de 16 à 64 Chocolats</a></li>
                        <li><a href="products.phtml">Coffret noir et lait de 16 à 64 Chocolats</a></li>
                        <li><a href="products.phtml">Atelier découverte</a></li>
                        <li><a href="products.phtml">Atelier enfant</a></li>
                        <li><a href="products.phtml">Atelier gourmet</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#CONFISERIES & CONFITES ">CONFISERIES & CONFITES</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Assortiment de pâtes de fruits 100g</a></li>
                        <li><a href="products.phtml">Assortiment de pâtes de fruits 160g</a></li>
                        <li><a href="products.phtml">Caramels mous fleur de sel framboise sésame</a></li>
                        <li><a href="products.phtml">Guimauves vanille, framboise</a></li>
                        <li><a href="products.phtml">Sucette lait</a></li>
                        <li><a href="products.phtml">Sucette noir</a></li>
                        <li><a href="products.phtml">Clémentines confites one</a></li>
                        <li><a href="products.phtml">Clémentines confitesbox</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#GANACHES & ORANGETTES CITRONNETTES">GANACHES & ORANGETTES
                        CITRONNETTES</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Basilic</a></li>
                        <li><a href="products.ph.tml">Café noir</a></li>
                        <li><a href="products.phtml">Citron</a></li>
                        <li><a href="products.phtml">Earl Grey noir</a></li>
                        <li><a href="products.phtml">Framboise</a></li>
                        <li><a href="products.phtml">Jasmin</a></li>
                        <li><a href="products.phtml">L'amoureux noir</a></li>
                        <li><a href="products.phtml">Menthe</a></li>
                        <li><a href="products.phtml">Passion</a></li>
                        <li><a href="products.phtml">Venezuela 72%</a></li>
                        <li><a href="products.phtml">Vietnam 64%</a></li>
                        <li><a href="products.phtml">Citronnettes</a></li>
                        <li><a href="products.phtml">Gingembrettes</a></li>
                        <li><a href="products.phtml">Orangettes</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#MADELEINES & BISCUITS LES PÂTES À TARTINER">MADELEINES & BISCUITS LES
                        PÂTES À TARTINER</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Biscuits noisette à la pâte à tartiner</a></li>
                        <li><a href="products.phtml">Madeleines Noir ou lait</a></li>
                        <li><a href="products.phtml">Madeleines noir</a></li>
                        <li><a href="products.phtml">Caramel fleur de sel</a></li>
                        <li><a href="products.phtml">Pâte à tartiner à la noisette Piémont</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#PRALINÉS">PRALINÉS</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Praliné Amandes Lait</a></li>
                        <li><a href="products.phtml">Praliné Amandes & Noisettes Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Praliné Amandes & Noisettes Noir</a></li>
                        <li><a href="products.phtml">Praliné Feuilletine Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Cacahuètes Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Coco Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Feuilletine Lait</a></li>
                        <li><a href="products.phtml">Praliné Noisettes Piémont Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Noix de pécan et fleur de sel</a></li>
                        <li><a href="products.phtml">Praliné Pignons de pin Noir ou Lait</a></li>
                        <li><a href="products.phtml">Praliné Sésame Noir ou Lait</a></li>
                    </ul>
                </li>
                <li class="nav-bar"><a href="#TABLETTES & MOULES ">TABLETTES & MOULES</a>
                    <ul class="sous">
                        <li><a href="products.phtml">Tablette Bali 68%</a></li>
                        <li><a href="products.phtml">Tablette Bélize 75%</a></li>
                        <li><a href="products.phtml">Tablette Grenade 65%</a></li>
                        <li><a href="products.phtml">Tablette lait République Dominicaine 46%</a></li>
                        <li><a href="products.phtml">Tablette Madagascar 50%</a></li>
                        <li><a href="products.phtml">Tablette Madagascar 68%</a></li>
                        <li><a href="products.phtml">Tablette Venezuela 72%</a></li>
                        <li><a href="products.phtml">Tablette Pérou 70%</a></li>
                        <li><a href="products.phtml">Tablette sans sucre 72%</a></li>
                        <li><a href="products.phtml">Tablette Venezuela 100%</a></li>
                        <li><a href="products.phtml">Tablette Vietnam 64%</a></li>
                        <li><a href="products.phtml">Animaux</a></li>
                        <li><a href="products.phtml">Oeuf Noir et Lait</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    <!---->
    <!---->

    <!--CONTENUE PRINCIPALE-->
    <main class="container">
        <section>
            <h1>La Selection du Moment</h1>
            <!--<article></article>

                Nous vous remercions par avance pour votre soutien, prenez soin de vous et à bientôt!
                </p>Réaliser pop up covid!-->

            <!-- TEST SLICK START -->

            <!-- TEST SLICK END -->
            <!--SLIDER START-->
            <div class="slider2">
                <?php foreach($products as $product): ?>
                <div><img src="<?= $product['Photos']?>" alt="<?= $product['Name'] ?>"></div>
                <?php endforeach ?>
            </div>

            <!--END SLIDER-->
        </section>
        <!---->
        <section>



        </section>
        <!---->
        <section>
            <h2>Les Amoureux du chocolat</h2>
            <article>
                <!--SLIDE img-->
                <div class="selection">
                    <div class="box">
                        <figure>
                            <img src="img/Praliné amandesnoisettes lait.jpg" width="260" alt="pralin">
                            <h3>Nos Pralinés</h3>
                        </figure>
                    </div>
                    <div class="box">
                        <figure>
                            <img src="img/nos-creations.jpg" width="260" alt="Les Artisans">
                            <h3>Nos Créations</h3>
                        </figure>
                    </div>
                    <div class="box">
                        <figure>
                            <img src="img/Passion.jpg" width="260" alt="pot">
                            <!--Réajuster taille image avec width and heigth-->
                            <h3>Nos Délices</h3>
                        </figure>
                    </div>
                </div>
            </article>

            <article>
                <div class="post">
                    <a target="_blanck" href="about_us.phtml"><img src="img/choco-bg-ft.jpg"></a>
                    <div class="text">
                        <h4>Qui nous sommes?</h4>
                        <div class="post-s">
                            <a target="_blanck" href="about_us.phtml">
                                <p>Qui nous sommes?</p>
                            </a>
                            <div class="btn-more">
                                <a target="_blanck" href="about_us.phtml"><span>En savoir plus</span></a>
                            </div>
                        </div>
                    </div>
                </div>

                <!--START BUTTON TOP-->
                <div class="top"></div>
                <a id="backtotop"><i class="fas fa-chevron-up"></i></a>
                <!--END BUTTON TOP-->
            </article>


        </section>


        <div class="row">
            <div>
                <div>
                    <div>
                        <div>
                            <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>

    <!--FOOTER-->
    <footer class="foot">
        <div class="lettre">
            <fieldset>
                <label for="lettre">Lettre d'informations <i class="fas fa-envelope"></i></label>
                <input type="text" id="lettre" placeholder="Saisissez votre adresse e-mail" required>
                <button class="btn-letter" type="submit">Envoyer</button>
            </fieldset>
        </div>
        <div>
            <a href="#">PAIEMENT SÉCURISÉ <i class="fas fa-lock"></i></a>
            <a href="#">CONDITIONS DE LIVRAISON <i class="fas fa-truck"></i></a>
            <a href="#">RETRAIT EN BOUTIQUE <i class="fas fa-store-alt"></i></a>
        </div>

        <div class="contact">
            <a href="">
                <h4>Informations</h4>
            </a>
            <a href="#"> Mentions légales</a>
            <a href="#">Conditions de livraison</a>
            <a href="#">Conditions générales de vente</a>
            <a href="#">Paiements sécurisés</a>
            <a href="#">Politique d'utilisation des cookies</a>
        </div>

        <div>
            <p>Copyright © 2015 par Les Amoureux du Chocolat. Tous droits réservés. 812 329 936 R.C.S Evry</p>
        </div>

        <div>
            <a target="_blanck" href="https://www.facebook.com/lesamoureuxduchocolat"><i
                    class="fab fa-facebook"></i></a>
            <a target="_blanck" href="https://www.instagram.com/lesamoureuxduchocolat/"><i
                    class="fab fa-instagram"></i></a>
        </div>
    </footer>
    <!--END of FOOTER-->

    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/jquery.backtotop.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>


</body>

</html>