	<?php if (array_key_exists( 'role', $_SESSION )) {?>


	<section>
	    <h1>La Selection du Moment</h1>
	    <div class="ligne-moment"></div>
	    <!--<article></article>

                Nous vous remercions par avance pour votre soutien, prenez soin de vous et à bientôt!
                </p>Réaliser pop up covid!-->

	    <!-- TEST SLICK START -->

	    <!-- TEST SLICK END -->
	    <!--SLIDER START-->

	    <!--center test a modifier-->
	    <center>
	        <div class="slider">
	            <?php foreach($products as $product): ?>
	            <img src="<?= $product['Photos']?>" alt="<?= $product['Name'] ?>">
	            <?php endforeach ?>
	        </div>
	    </center>

	    <!--END SLIDER-->
	</section>
	<!---->
	<section>
	</section>
	<!---->
	<section>
	    <h2>Les Amoureux du chocolat</h2>
	    <article>
	        <!--SLIDE img-->
	        <div class="selection">
	            <div class="box">
	                <figure>
	                    <img src="img/Praliné-amandesnoisettes-lait-redi.jpg" alt="pralin">
	                    <h3>Nos Pralinés</h3>
	                </figure>
	            </div>
	            <div class="box">
	                <figure>
	                    <img src="img/Moules-fox-redi" alt="fox">
	                    <h3>Nos Créations</h3>
	                </figure>
	            </div>
	            <div class="box">
	                <figure>
	                    <img src="img/Passion.jpg" alt="pot">
	                    <!--Réajuster taille image avec width and heigth-->
	                    <h3>Nos Délices</h3>
	                </figure>
	            </div>
	        </div>
	    </article>
	    <div class="ligne"></div>
	    <article>
	        <div class="post">
	            <a target="_blanck" href="about_us.phtml"><img src="img/choco-bg-ft.jpg"></a>
	            <div class="text">
	                <h4>Qui nous sommes?</h4>
	                <div class="post-s">
	                    <a target="_blanck" href="about_us.phtml">
	                        <p>Qui nous sommes?</p>
	                    </a>
	                    <div class="btn-more">
	                        <a target="_blanck" href="about_us.phtml"><span>En savoir plus</span></a>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <!--START BUTTON TOP-->
	        <div class="top"></div>
	        <a id="backtotop"><i class="fas fa-chevron-up"></i></a>
	        <!--END BUTTON TOP-->
	    </article>


	</section>





	<?php } else { ?>


	<section>
	    <h1>La Selection du Moment</h1>
	    <div class="ligne-moment"></div>
	    <!--<article></article>

                Nous vous remercions par avance pour votre soutien, prenez soin de vous et à bientôt!
                </p>Réaliser pop up covid!-->

	    <!--SLIDER START-->
	    <center>
	        <div class="slider">
	            <?php foreach($products as $product): ?>
	            <img src="<?= $product['Photos']?>" alt="<?= $product['Name'] ?>">
	            <?php endforeach ?>
	        </div>
	    </center>

	    <!--END SLIDER-->
	</section>

	<section>
	    <h2>Les Amoureux du chocolat</h2>
	    <article>
	        <!--BOX TROIS IMAGES img-->
	        <div class="selection">
	            <div class="box">
	                <figure>
	                    <img src="img/Praliné-amandesnoisettes-lait-redi.jpg" alt="pralin">
	                    <h3>Nos Pralinés</h3>
	                </figure>
	            </div>
	            <div class="box">
	                <figure>
	                    <img src="img/Moules-fox-redi" alt="fox">
	                    <h3>Nos Créations</h3>
	                </figure>
	            </div>
	            <div class="box">
	                <figure>
	                    <img src="img/Passion.jpg" alt="pot">
	                    <h3>Nos Délices</h3>
	                </figure>
	            </div>
	        </div>
	    </article>
	    <!-- <div class="ligne"></div> -->
	    <article>
	        <div class="post">
	            <a target="_blanck" href="about_us.phtml"><img src="img/choco-bg-ft.jpg"></a>
	            <div class="text">
	                <h4>Qui nous sommes?</h4>
	                <div class="post-s">
	                    <a target="_blanck" href="about_us.phtml">
	                        <!-- <p>Qui nous sommes?</p> -->
	                    </a>
	                    <div class="btn-more">
	                        <a target="_blanck" href="about_us.phtml"><span>En savoir plus</span></a>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <!--START BUTTON TOP-->
	        <div class="top"></div>
	        <a id="backtotop"><i class="fas fa-chevron-up"></i></a>
	        <!--END BUTTON TOP-->
	    </article>


	</section>


	<?php } ?>