<form class="generic-form container" action="login.php" method="post">
    <fieldset>
        <legend class="fa fa-sticky-note-o">
            <img src="img/logo_header.png">
            <h1>Connection</h1>
        </legend>
        <input type="text" placeholder="email" name="email" />
        <input type="password" placeholder="password" name="psw" />
        <input type="submit" value="connect" />
    </fieldset>
</form>
<div>
    <a href="forgotPassword.php">Mot de passe oublié ?</a>
</div>