<form class="generic-form container" action="register.php" method="POST">

    <fieldset>

        <legend class="fa fa-sticky-note-o">
            <img class="imgheader" src="img/logo_header.png">
            <h1>S'enregistrer</h1>
        </legend>
        <input type="text" placeholder="prénom" name="firstName">
        <input type="text" placeholder="nom" name="lastName">
        <input type="text" placeholder="age" name="age">
        <input type="text" placeholder="mail" name="email">
        <input type="text" placeholder="password" name="psw">
        <input type="submit" value="envoyer" />



    </fieldset>



</form>